branches-template:
  - main: "{{ref-name}}-{{name}}-{{timestamp}}.{{runNumber}}"
  - "feature/*": "{{ref-name}}-{{timestamp}}.{{runNumber}}"
  - "hotfix/*": "{{ref-name}}-{{timestamp}}.{{runNumber}}"
  - "fix/*": "{{ref-name}}-{{timestamp}}.{{runNumber}}"
  - tag: "v{{major}}.{{minor}}.{{patch}}"
dist-tags:
  - main: "latest"